#ifndef MICROTEX_OTFCONFIG_H
#define MICROTEX_OTFCONFIG_H

#define GLYPH_RENDER_TYPE_BOTH 0
#define GLYPH_RENDER_TYPE_PATH 1
#define GLYPH_RENDER_TYPE_TYPEFACE 2

// clang-format off
// if have glyph render path
#if GLYPH_RENDER_TYPE == GLYPH_RENDER_TYPE_BOTH || GLYPH_RENDER_TYPE == GLYPH_RENDER_TYPE_PATH
#   define HAVE_GLYPH_RENDER_PATH
#endif

#if GLYPH_RENDER_TYPE == GLYPH_RENDER_TYPE_BOTH || GLYPH_RENDER_TYPE == GLYPH_RENDER_TYPE_TYPEFACE
#   define HAVE_GLYPH_RENDER_TYPEFACE
#endif
// clang-format on

#endif  // MICROTEX_OTFCONFIG_H
