front_src = [
    'front/ast.cpp',
    'front/expander.cpp',
    'front/front.cpp',
    'front/lexer.cpp',
    'front/lower.cpp',
    'front/parser.cpp',
    'front/prelude.cpp',
    'front/spec.cpp'
]

if install_headerfiles
    install_headers([
        'ast.h',
        'diagnostics.h',
        'expander.h',
        'front.h',
        'hooks.h',
        'input_mode.h',
        'lexer.h',
        'lower.h',
        'parser.h',
        'prelude.h',
        'spec.h',
        'token.h'
    ], subdir: 'microtex/front')
endif
