core_src = [
    'core/formula.cpp',
    'core/formula_def.cpp',
    'core/glue.cpp',
    'core/localized_num.cpp',
    'core/split.cpp'
]

if install_headerfiles
	install_headers([
        'formula.h',
        'glue.h',
        'localized_num.h',
        'split.h'
	], subdir: 'microtex/core')
endif
